const DAY_MS = 86400000;
const today = new Date("2026-05-25T09:00:00+08:00");

const roles = {
  encoder: {
    label: "Encoder / Receiving Staff",
    title: "Application Intake Dashboard",
    description: "Encode incoming applications, initialize completeness-check records, and monitor new intake tasks.",
    visibility: "assigned",
  },
  cc: {
    label: "SSD Technical Staff / CC Preparer",
    title: "Completeness Check Workspace",
    description: "Review documentary requirements, revise returned forms, and submit completed assessments for review.",
    visibility: "assigned",
  },
  manager: {
    label: "Team Manager / Supervisor",
    title: "SSRCS Team Control Dashboard",
    description: "Review completeness assessments and packages, balance workload, and act on delayed cases.",
    visibility: "team",
  },
  chief: {
    label: "Division Chief",
    title: "SSRCS Oversight Dashboard",
    description: "Approve completeness outcomes and monitor SLA, routing, documentation, and governance indicators.",
    visibility: "all",
  },
  reviewer: {
    label: "Technical Reviewer",
    title: "Technical Review Workspace",
    description: "Complete critical-area findings and recommendations and submit review records for internal validation.",
    visibility: "assigned",
  },
  validator: {
    label: "Internal Validator",
    title: "Technical Validation Dashboard",
    description: "Validate submitted technical findings, review annexes, and return records needing correction.",
    visibility: "validation",
  },
  custodian: {
    label: "Document Custodian / Records Officer",
    title: "Routing and Records Dashboard",
    description: "Generate approved packages, track signature routing, upload signed records, and complete tagging.",
    visibility: "records",
  },
  executive: {
    label: "Authorized Executive / ANS",
    title: "Executive Oversight Dashboard",
    description: "Monitor institutional throughput, timeliness, routing backlog, and records governance performance.",
    visibility: "all",
  },
  sqa: {
    label: "CS-SQA",
    title: "Systems Quality Assurance Dashboard",
    description: "Monitor security testing, blocked control attempts, vulnerabilities, remediation, and retesting.",
    visibility: "audit",
  },
  admin: {
    label: "System Administrator",
    title: "Portal Administration Dashboard",
    description: "Control users, roles, reference lists, template versions, SLA rules, and system audit alerts.",
    visibility: "all",
  },
};

const users = {
  encoder: { password: "demo123", name: "Paolo Reyes", office: "SS-SSD", roles: ["encoder"] },
  ccstaff: { password: "demo123", name: "Liza Ramos", office: "SS-SSD", roles: ["cc"] },
  manager: { password: "demo123", name: "Marco Santos", office: "SSRCS Team", roles: ["manager"] },
  chief: { password: "demo123", name: "Division Chief", office: "Statistical Standards Division", roles: ["chief"] },
  reviewer: { password: "demo123", name: "Tina Cruz", office: "SSRCS Team", roles: ["reviewer"] },
  validator: { password: "demo123", name: "Victor de la Cruz", office: "SS-SSD", roles: ["validator"] },
  records: { password: "demo123", name: "Rina Garcia", office: "SS-SSD Records", roles: ["custodian"] },
  executive: { password: "demo123", name: "Authorized Executive", office: "Standards Service", roles: ["executive"] },
  sqa: { password: "demo123", name: "CS-SQA Officer", office: "Systems Quality Assurance", roles: ["sqa"] },
  admin: { password: "demo123", name: "Portal Administrator", office: "System Administration", roles: ["admin"] },
  multi: { password: "demo123", name: "Andrea Lim", office: "SSRCS Team", roles: ["reviewer", "custodian"] },
};

const phaseMap = {
  "Submitted / Encoded": "Intake",
  "CC Form Created": "Completeness Check",
  "Under Completeness Check": "Completeness Check",
  "For Team Manager Review": "Completeness Check",
  "For Division Chief Approval": "Completeness Check",
  "CC Approved - Complete": "Completeness Check",
  "CC Approved - Deficient": "Completeness Check",
  "CC Form Released to Applicant": "Applicant Notification",
  "CC Deficiency Form Released to Applicant": "Applicant Notification",
  "Awaiting Completion Submission": "Applicant Action",
  "Completion Submission Received": "Applicant Action",
  "Accepted for Technical Review": "Formal Review",
  "Technical Review Form Created": "Formal Review",
  "Under Technical Review": "Formal Review",
  "Under Internal Validation": "Formal Review",
  "Review Package Generated": "Package Preparation",
  "For Team Manager / Supervisor Review": "Package Review",
  "Cleared for External Routing": "Routing",
  "Package Exported / Printed": "Routing",
  "Externally Routed for Signature": "Routing",
  "Returned from External Routing - For Correction": "Routing",
  "Signature Declined / Decision Reconsideration": "Routing",
  "Signed Package Uploaded": "Final Documentation",
  "Signed Package Verification": "Final Documentation",
  "Signed Package Re-upload Required": "Final Documentation",
  "Tagged and Documented": "Final Documentation",
  Closed: "Closure",
};

const cases = [
  {
    id: "SSRCS-2026-001",
    activity: "Quarterly Fisheries Surveys",
    agency: "PSA - Economic Sector Statistics Service",
    assigned: { cc: "Liza Ramos", reviewer: "Tina Cruz", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "For Division Chief Approval",
    lastUpdated: "2026-05-23",
    received: "2026-05-15",
    ccOutcome: "Complete",
    decision: "Pending",
    ccApproved: false,
    ccReleased: false,
    accepted: false,
    reviewValidated: false,
    packageVersion: null,
    routedVersion: null,
    signedUploaded: false,
    signedVerified: false,
    tagged: false,
    ccWithinSla: true,
    reviewWithinSla: null,
  },
  {
    id: "SSRCS-2026-002",
    activity: "Labor Force Survey Module Enhancement",
    agency: "PSA - Social Sector Statistics Service",
    assigned: { cc: "Liza Ramos", reviewer: "Tina Cruz", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "Under Technical Review",
    lastUpdated: "2026-05-21",
    received: "2026-05-06",
    ccOutcome: "Complete",
    decision: "Pending",
    ccApproved: true,
    ccReleased: true,
    accepted: true,
    reviewValidated: false,
    packageVersion: null,
    routedVersion: null,
    signedUploaded: false,
    signedVerified: false,
    tagged: false,
    ccWithinSla: true,
    reviewWithinSla: null,
  },
  {
    id: "SSRCS-2026-003",
    activity: "National Nutrition Monitoring Survey",
    agency: "Department of Health",
    assigned: { cc: "Liza Ramos", reviewer: "Andrea Lim", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "CC Approved - Deficient",
    lastUpdated: "2026-05-20",
    received: "2026-05-14",
    ccOutcome: "Incomplete - Missing Documents",
    decision: "Pending",
    ccApproved: true,
    ccReleased: false,
    accepted: false,
    reviewValidated: false,
    packageVersion: null,
    routedVersion: null,
    signedUploaded: false,
    signedVerified: false,
    tagged: false,
    ccWithinSla: true,
    reviewWithinSla: null,
  },
  {
    id: "SSRCS-2026-004",
    activity: "Commodity Flow Survey",
    agency: "PSA - Trade Statistics Division",
    assigned: { cc: "Liza Ramos", reviewer: "Tina Cruz", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "For Team Manager / Supervisor Review",
    lastUpdated: "2026-05-18",
    received: "2026-04-24",
    ccOutcome: "Complete",
    decision: "Clearance Granted",
    ccApproved: true,
    ccReleased: true,
    accepted: true,
    reviewValidated: true,
    packageVersion: 2,
    routedVersion: null,
    signedUploaded: false,
    signedVerified: false,
    tagged: false,
    ccWithinSla: false,
    reviewWithinSla: false,
  },
  {
    id: "SSRCS-2026-005",
    activity: "Tourism Establishment Survey",
    agency: "Department of Tourism",
    assigned: { cc: "Liza Ramos", reviewer: "Andrea Lim", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "Externally Routed for Signature",
    lastUpdated: "2026-05-12",
    received: "2026-04-08",
    ccOutcome: "Complete",
    decision: "Clearance Granted",
    ccApproved: true,
    ccReleased: true,
    accepted: true,
    reviewValidated: true,
    packageVersion: 1,
    routedVersion: 1,
    signedUploaded: false,
    signedVerified: false,
    tagged: false,
    ccWithinSla: true,
    reviewWithinSla: true,
  },
  {
    id: "SSRCS-2026-006",
    activity: "ICT Usage Survey of Enterprises",
    agency: "Department of Information and Communications Technology",
    assigned: { cc: "Liza Ramos", reviewer: "Tina Cruz", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "Signed Package Verification",
    lastUpdated: "2026-05-24",
    received: "2026-04-18",
    ccOutcome: "Complete",
    decision: "Clearance Granted",
    ccApproved: true,
    ccReleased: true,
    accepted: true,
    reviewValidated: true,
    packageVersion: 3,
    routedVersion: 3,
    signedUploaded: true,
    signedVerified: false,
    tagged: false,
    ccWithinSla: true,
    reviewWithinSla: true,
  },
  {
    id: "SSRCS-2026-007",
    activity: "Household Energy Consumption Survey",
    agency: "Department of Energy",
    assigned: { cc: "Liza Ramos", reviewer: "Tina Cruz", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "Tagged and Documented",
    lastUpdated: "2026-05-24",
    received: "2026-04-02",
    ccOutcome: "Complete",
    decision: "Clearance Granted",
    ccApproved: true,
    ccReleased: true,
    accepted: true,
    reviewValidated: true,
    packageVersion: 1,
    routedVersion: 1,
    signedUploaded: true,
    signedVerified: true,
    tagged: true,
    ccWithinSla: true,
    reviewWithinSla: true,
  },
  {
    id: "SSRCS-2026-008",
    activity: "Regional Employment Expectations Survey",
    agency: "Department of Labor and Employment",
    assigned: { cc: "Liza Ramos", reviewer: "Tina Cruz", validator: "Victor de la Cruz", custodian: "Rina Garcia" },
    status: "Closed",
    lastUpdated: "2026-05-09",
    received: "2026-03-18",
    ccOutcome: "Complete",
    decision: "Clearance Granted",
    ccApproved: true,
    ccReleased: true,
    accepted: true,
    reviewValidated: true,
    packageVersion: 2,
    routedVersion: 2,
    signedUploaded: true,
    signedVerified: true,
    tagged: true,
    ccWithinSla: true,
    reviewWithinSla: true,
  },
];

let activities = [
  ["Division Chief", "Division Chief", "Endorsed CC form reviewed for approval", "SSRCS-2026-001", "25 May 2026, 08:35", "Pending"],
  ["Rina Garcia", "Document Custodian / Records Officer", "Signed package uploaded for verification", "SSRCS-2026-006", "24 May 2026, 16:10", "Completed"],
  ["Tina Cruz", "Technical Reviewer", "Review package generated, version 2", "SSRCS-2026-004", "18 May 2026, 14:20", "Completed"],
  ["Rina Garcia", "Document Custodian / Records Officer", "Package routed externally for signature", "SSRCS-2026-005", "12 May 2026, 10:18", "Pending"],
  ["CS-SQA Officer", "CS-SQA", "Blocked closure attempt without signed upload", "SSRCS-2026-005", "12 May 2026, 10:24", "Blocked"],
];

const vulnerabilities = [
  { id: "VAPT-004", severity: "High", module: "Attachment Access", finding: "Direct-document authorization regression", status: "For Retest" },
  { id: "VAPT-009", severity: "Medium", module: "Session Control", finding: "Idle timeout configuration review", status: "Under Remediation" },
  { id: "VAPT-011", severity: "Low", module: "Headers", finding: "Security header enhancement", status: "Open" },
];

const templateVersions = [
  ["Completeness Check Form", "v1.1 Corrected", "For approval"],
  ["Integrated Forms 3 and 4", "v1.1 Corrected", "For approval"],
  ["Applicant Letter", "v1.1 Corrected", "For approval"],
  ["Clearance Memorandum", "v1.0 Reviewed", "Active candidate"],
];

const ccRequirementCatalog = [
  ["A", "Letter addressed to the NSCRG", "A1-A3"],
  ["B", "Accomplished SSRCS Form 1", "B1-B10"],
  ["C", "Survey Questionnaires (PAPI / CAPI / CAWI)", "C1-C2"],
  ["D", "Survey Manual / Manual of Instructions", "D1-D2"],
  ["E", "Compilation of Policy Uses of Survey Results", "E1"],
  ["F", "List of Tables to be Generated", "F1-F2"],
  ["G", "Survey Proposal", "G1"],
  ["H", "SSRCS Form 4 for Previously Cleared Survey", "H1"],
];

const criticalAreaCatalog = [
  ["CA 1", "Necessity of conducting the survey"],
  ["CA 2", "Avoiding unnecessary duplication of data"],
  ["CA 3", "Sampling design, accuracy and representativeness"],
  ["CA 4", "Alignment of form content with intended tables"],
  ["CA 5", "Operational plan feasibility and effectiveness"],
  ["CA 6", "Statistical output quality and relevance"],
  ["CA 7", "Instrument accuracy and compliance"],
];

const caseWorkspaces = {};

const state = {
  user: null,
  role: null,
  view: "dashboard",
  cardFilter: null,
  filters: { search: "", phase: "", status: "", agency: "", staff: "", period: "" },
  selectedCase: null,
  caseTab: "overview",
};

function buildCaseWorkspace(caseItem) {
  if (caseWorkspaces[caseItem.id]) return caseWorkspaces[caseItem.id];
  const deficient = caseItem.ccOutcome.includes("Incomplete");
  caseWorkspaces[caseItem.id] = {
    profile: {
      transactionNo: caseItem.id,
      title: caseItem.activity,
      proponent: caseItem.agency,
      conducting: caseItem.agency,
      receivedDate: caseItem.received,
      previouslyCleared: caseItem.id === "SSRCS-2026-004" ? "Yes" : "No",
    },
    completeness: ccRequirementCatalog.map(([code, description, proof], index) => {
      const applicable = code !== "H" || caseItem.id === "SSRCS-2026-004";
      return {
        code,
        description,
        proof,
        applicable,
        level: !applicable ? "Not Applicable" : deficient && index < 2 ? "Not Submitted" : "Full",
        remarks: applicable && deficient && index < 2 ? "Please submit this document." : "",
      };
    }),
    clarifications: deficient ? ["Missing signed letter and accomplished SSRCS Form 1."] : [],
    findings: criticalAreaCatalog.map(([code, area], index) => ({
      code,
      area,
      rating: index === 4 || index === 5 ? "Partial" : "Full",
      observation: index === 4 ? "Timeline sequencing requires confirmation." : "",
      recommendation: index === 4 ? "Align operational milestones before implementation." : "",
    })),
    documents: [
      { name: "SSRCS Form 3 - PSA Action Notification Form", status: caseItem.packageVersion ? `Version ${caseItem.packageVersion}` : "Pending generation", required: true },
      { name: "Annex A - Supporting Proof / Observations", status: caseItem.packageVersion ? "Generated" : "Pending generation", required: true },
      { name: "Annex B - Recommendations", status: caseItem.packageVersion ? "Generated" : "Pending generation", required: true },
      { name: caseItem.agency.startsWith("PSA") ? "Clearance Memorandum" : "Letter to Applicant Agency", status: caseItem.packageVersion ? "Generated" : "Pending generation", required: true },
      { name: "SSRCS Form 4 - Monitoring Form", status: caseItem.packageVersion ? "Included for issuance" : "Pending generation", required: false },
    ],
    routing: {
      exportedDate: caseItem.routedVersion ? "2026-05-11" : "",
      routingDate: caseItem.routedVersion ? "2026-05-12" : "",
      returnedDate: caseItem.signedUploaded ? "2026-05-24" : "",
      fileName: caseItem.signedUploaded ? `${caseItem.id}_Signed_Package.pdf` : "",
      metadataTags: caseItem.tagged ? "Signed final package; SSRCS; Decision record" : "",
      versionHash: caseItem.signedVerified ? "Verified SHA-256 evidence recorded" : "",
    },
  };
  return caseWorkspaces[caseItem.id];
}
